ENH: Better explain in error how to reuse previously typed message if refused
     Previously, if a commit message got refused, the following error message
     was shown

       To continue editing, run the command
          git commit -e -F .git/COMMIT_MSG
       (assuming your working directory is at the top)

     Dom complained he did never manage to locate the file COMMIT_MSG and
     prefers to be presented with the absolute path to the file. Unfortunately,
     that is not possible as this hook is run on the server which is not
     necessarily the same machine as where one is pushing from. In any case,
     it's a different process running the hook and therefore there is no way of
     determining the current working directory of the pushing process.

     Nonetheless, the new error message tries to come up with a good enough
     solution by showing a series of commands that should do the trick (at
     least on systems employing Unix-style forward slash directory separators).

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -9,13 +9,19 @@ commit_msg="$GIT_DIR/COMMIT_MSG"
 sed -n -e '/^#/d' -e '/^diff --git/q' -e 'p;d' "$1" > "$commit_msg"
 
 die() {
-	echo 'commit-msg hook failure' 1>&2
-	echo '-----------------------' 1>&2
-	echo '' 1>&2
-	echo "$@" 1>&2
-	echo 'To continue editing, run the command
-  git commit -e -F '"$commit_msg"'
-(assuming your working directory is at the top).' 1>&2
+        echo 'commit-msg hook failure' 1>&2
+        echo '-----------------------' 1>&2
+        echo '' 1>&2
+        echo "$@" 1>&2
+        echo 'To continue editing, identify the location of your .git directory to locate and
+re-use the previously typed message by running the command
+
+  git commit -e -F `git rev-parse --git-dir`/COMMIT_MSG
+
+You may want to additionally specify any commit option you used previously,
+e.g. --amend or --signoff.
+
+' 1>&2
 	exit 1
 }
 
