ENH: Made make check output more verbose
Signed-off-by: Dirk Ribbrock <dirk.ribbrock@math.uni-dortmund.de>

diff --git a/test_system/run_tests b/test_system/run_tests
--- a/test_system/run_tests
+++ b/test_system/run_tests
@@ -9,18 +9,47 @@
 
 usage() {
 
-    echo "Usage: runtests file [files...]"
+    echo "Usage: run_tests file [files...]"
     echo "(if \"file\" is a directory, run recursively all tests)"
     exit 1
 
 }
 
-#if test -z "" ; then
-#    usage
-#fi
+if test -z "$1" ; then
+  usage
+fi
 
-find "$@" -type f -name '*-test' | \
-while read f ; do
-  echo $f:
-  $f
+all=0;
+failed=0;
+rv=0
+tests=$(find "$1" -type f -name '*-test')
+
+for tst in $tests; do
+  echo $tst:
+  $tst
+  rv=$?
+  all=$(( $all + 1 ));
+  if [ "$rv" -ne 0 ]; then
+    failed=$(( $failed + 1 ));
+    fnames="$fnames $tst"
+  fi
 done
+
+if [ "$failed" -eq 0 ]; then
+  banner="All $all tests passed";
+else
+  banner="$failed of $all tests failed";
+fi;
+dashes=`echo "$banner" | sed s/./=/g`;
+echo $dashes
+echo $banner;
+echo $dashes
+if [ "$failed" -eq 0 ]; then
+  exit 0
+else
+  echo "List of failed tests:"
+  for tst in $fnames; do
+    echo $tst
+  done
+    exit 1
+fi;
